/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    products: Product;
    media: Media;
    product_files: ProductFile;
    orders: Order;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
}

export interface User {
  id: string;
  email: string;
  password: string | null;

  // Optional verification/login fields
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;

  // Relations
  products?: (string | Product)[] | null;
  product_files?: (string | ProductFile)[] | null;

  role: 'admin' | 'user';
  updatedAt: string;
  createdAt: string;
}

export interface Product {
  id: string;
  name: string;
  description?: string | null;
  category: 'ui_kits' | 'icons';
  price: number; // ✅ In NGN

  approvedForSale?: 'pending' | 'approved' | 'denied' | null;

  // Relations
  user?: string | User | null;
  product_files: string | ProductFile;
  images: {
    image: string | Media;
    id?: string | null;
  }[];

  // Paystack integration
  paystackProductId: string;
  paystackPrice?: number;
  paystackCurrency?: string;

  updatedAt: string;
  createdAt: string;
}

export interface ProductFile {
  id: string;
  user?: string | User | null;

  // Upload metadata
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;

  updatedAt: string;
  createdAt: string;
}

export interface Media {
  id: string;
  user?: string | User | null;

  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;

  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };

  updatedAt: string;
  createdAt: string;
}

export interface Order {
  id: string;
  _isPaid: boolean;

  // Relations
  user: string | User;
  products: (string | Product)[];

  updatedAt: string;
  createdAt: string;
}

export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | { [key: string]: unknown }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}

export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
